# Generated by Django 4.2.5 on 2023-09-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='Person Name')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=240, verbose_name='Person Name')),
                ('business_name', models.CharField(max_length=240, verbose_name='Name of Business')),
                ('receipt_number', models.CharField(max_length=100, verbose_name='Receipt Number')),
                ('subtotal', models.CharField(max_length=20, verbose_name='Subtotal')),
            ],
        ),
    ]
