# Generated by Django 4.2.5 on 2023-09-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.CharField(default='01/11/1000', max_length=10, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
